### ISSUE TITLE
Auto-complete fails to work after newline.

### ISSUE THREAD

**Issue by sumanthvrao** [rr-/urwid_readline#10]
The autocomplete feature appears to not work when there have been two or more newlines. We can do as many auto-completes on the first line but one on the second line and none after.

Steps to reproduce based on the example in `example.py` : 

* First line autocomplete with TAB (works)
* Enter
* Second line autocomplete with TAB (works)
* Autocomplete on the second line again, or in subsequent third (or after) fails.

Error discovered while autocompleting users and streams in compose box of Zulip-terminal with the new changes  integrated  zulip/zulip-terminal#441

**Comment by rr-** [comment]
@sumanthvrao please check https://github.com/rr-/urwid_readline/commit/4087357f76409a57a0bd262160906733d13dcc2b

**Comment by sumanthvrao** [comment]
Thanks for the quick reply @rr- . Gave it a try but I'm afraid the issue still persists. I'm trying to run the example from the same example.py again.

**Comment by rr-** [comment]
@sumanthvrao `example.py` works against the installed version, did you install the patched version?

**Comment by sumanthvrao** [comment]
@rr- Oops. I was under the impression the example ran the local class instead. 

I can confirm that it is indeed working now. Thanks again @rr- . It would be good to have it as a part of the release :)

**Comment by rr-** [comment]
Thanks for testing. Fix should be available as 0.10 on pypi.
