### ISSUE TITLE
Cycle back on autocomplete

### ISSUE THREAD

**Issue by kaustubh-nair** [rr-/urwid_readline#11]
It would be nice to have an extra key for autocomplete to decrease the state. Can this be done on the current release? 
I can go ahead and send a PR, if you think this would be useful

**Comment by rr-** [comment]
It's not possible currently, but I'll gladly accept any pull requests.

**Comment by rr-** [comment]
Thanks for the PR, I've released it as 0.11 and it should be available on PyPI.

**Comment by kaustubh-nair** [comment]
Awesome, thanks!
