### ISSUE TITLE
Add placeholder text option in ReadlineEdit widget

### ISSUE THREAD

**Issue by Ezio-Sarthak** [rr-/urwid_readline#17]
It would be of great help if we could have a placeholder text like parameter in the `ReadlineEdit()` class :)

**Comment by neiljp** [comment]
I will leave @rr- to respond, but this seems achievable independently of `ReadlineEdit` through setting appropriate callbacks, or perhaps writing a mixin class for edit boxes in general - though perhaps there are nuances with particular key combinations related to readline?

**Comment by rr-** [comment]
Yeah, to me it sounds like out of scope for this library as well

**Comment by Ezio-Sarthak** [comment]
Yeah. My bad :sweat_smile:. Modifying callback functions should be a basic solution for such an issue :)
