### ISSUE TITLE
Support Multiline edit.

### ISSUE THREAD

**Issue by amanagr** [rr-/urwid_readline#4]
@rr- Does mutliline edit works for you?
If not, can you do a quick fix for that and a new release for the change?
Thanks!!

**Comment by rr-** [comment]
No, I never used it that way.
A PR is encouraged since it'll be tough for me to find time to work on it myself.

**Comment by amanagr** [comment]
@rr- thanks for the wonderful tweaks to my code.
I will send a PR in a few days to support the following features:
* Copy
* Paste
* Undo
* Redo
I am also waiting for a release.

**Comment by rr-** [comment]
I bumped the package version to 0.6; it should be available on PyPI shortly.
